<<<<<<< HEAD
<<<<<<< HEAD
[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
=======
[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
>>>>>>> 1276421bc5533155ea33ae5595adf3cc85cb0725
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
=======
# [phases.setup]
# nixPkgs = ["php83", "php83Packages.composer"]

# [phases.install]
# cmds = ["composer install --no-dev --optimize-autoloader"]

# [start]

# cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
>>>>>>> 862342fe2eac7159c8190e2d3f6e648ec1feaf76
